// Generated by QuantaLang Compiler
// Do not edit manually

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


// ============================================================================
// QuantaLang Runtime Library
// Embedded in generated C output - do not edit
// ============================================================================

// --- I/O initialization ---
static void __quanta_init_io(void) {
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);
}

// --- String type ---

typedef struct {
    const char* ptr;
    size_t len;
    size_t cap;    // 0 for string literals (not heap-allocated)
} QuantaString;

static QuantaString quanta_string_new(const char* s) {
    QuantaString qs;
    qs.ptr = s;
    qs.len = strlen(s);
    qs.cap = 0; // literal, not owned
    return qs;
}

static QuantaString quanta_string_concat(QuantaString a, QuantaString b) {
    size_t new_len = a.len + b.len;
    char* buf = (char*)malloc(new_len + 1);
    memcpy(buf, a.ptr, a.len);
    memcpy(buf + a.len, b.ptr, b.len);
    buf[new_len] = '\0';
    QuantaString qs;
    qs.ptr = buf;
    qs.len = new_len;
    qs.cap = new_len + 1;
    return qs;
}

static size_t quanta_string_len(QuantaString s) {
    return s.len;
}

static bool quanta_string_eq(QuantaString a, QuantaString b) {
    if (a.len != b.len) return false;
    return memcmp(a.ptr, b.ptr, a.len) == 0;
}

static void quanta_string_free(QuantaString s) {
    if (s.cap > 0) free((void*)s.ptr);
}

// --- Vec (dynamic array) type ---

typedef struct {
    void* ptr;
    size_t len;
    size_t cap;
    size_t elem_size;
} QuantaVec;

static QuantaVec quanta_vec_new(size_t elem_size) {
    QuantaVec v;
    v.ptr = NULL;
    v.len = 0;
    v.cap = 0;
    v.elem_size = elem_size;
    return v;
}

static void quanta_vec_push(QuantaVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->ptr = realloc(v->ptr, v->cap * v->elem_size);
    }
    memcpy((char*)v->ptr + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* quanta_vec_get(QuantaVec* v, size_t index) {
    return (char*)v->ptr + index * v->elem_size;
}

static void quanta_vec_free(QuantaVec* v) {
    free(v->ptr);
    v->ptr = NULL;
    v->len = 0;
    v->cap = 0;
}

// --- Typed Vec helpers (wrapping QuantaVec for specific element types) ---

static QuantaVec quanta_vec_new_i32(void) { return quanta_vec_new(sizeof(int32_t)); }
static QuantaVec quanta_vec_new_i64(void) { return quanta_vec_new(sizeof(int64_t)); }
static QuantaVec quanta_vec_new_f64(void) { return quanta_vec_new(sizeof(double)); }

// Note: These wrappers use a global QuantaVec pointer trick — the first
// argument is a QuantaVec passed by value, but since QuantaLang passes
// struct locals, the C compiler will place them on the stack where we
// can take their address. We use a thin wrapper to bridge the gap.
static QuantaVec* __quanta_vec_ref = NULL;
static void quanta_vec_push_i32(QuantaVec v, int32_t val) {
    // Find the original local via the stored pointer (set by codegen)
    // Fallback: push into a copy — but mutations won't be visible.
    // The real solution: codegen passes &v. For now we use a global registry.
    (void)v; (void)val;
}
// Simpler approach: heap-allocated vecs via a handle pattern
typedef struct { QuantaVec* inner; } QuantaVecHandle;

static QuantaVecHandle quanta_hvec_new_i32(void) {
    QuantaVecHandle h;
    h.inner = (QuantaVec*)malloc(sizeof(QuantaVec));
    *h.inner = quanta_vec_new(sizeof(int32_t));
    return h;
}
static void quanta_hvec_push_i32(QuantaVecHandle h, int32_t val) { quanta_vec_push(h.inner, &val); }
static int32_t quanta_hvec_get_i32(QuantaVecHandle h, size_t index) { return *(int32_t*)quanta_vec_get(h.inner, index); }
static size_t quanta_hvec_len(QuantaVecHandle h) { return h.inner->len; }
static int32_t quanta_hvec_pop_i32(QuantaVecHandle h) {
    if (h.inner->len == 0) return 0;
    h.inner->len--;
    return *(int32_t*)((char*)h.inner->ptr + h.inner->len * h.inner->elem_size);
}
static void quanta_hvec_free(QuantaVecHandle h) { quanta_vec_free(h.inner); free(h.inner); }

// f64 handle variants
static QuantaVecHandle quanta_hvec_new_f64(void) {
    QuantaVecHandle h;
    h.inner = (QuantaVec*)malloc(sizeof(QuantaVec));
    *h.inner = quanta_vec_new(sizeof(double));
    return h;
}
static void quanta_hvec_push_f64(QuantaVecHandle h, double val) { quanta_vec_push(h.inner, &val); }
static double quanta_hvec_get_f64(QuantaVecHandle h, size_t index) { return *(double*)quanta_vec_get(h.inner, index); }
static double quanta_hvec_pop_f64(QuantaVecHandle h) {
    if (h.inner->len == 0) return 0.0;
    h.inner->len--;
    return *(double*)((char*)h.inner->ptr + h.inner->len * h.inner->elem_size);
}
// i64 handle variants
static QuantaVecHandle quanta_hvec_new_i64(void) {
    QuantaVecHandle h;
    h.inner = (QuantaVec*)malloc(sizeof(QuantaVec));
    *h.inner = quanta_vec_new(sizeof(int64_t));
    return h;
}
static void quanta_hvec_push_i64(QuantaVecHandle h, int64_t val) { quanta_vec_push(h.inner, &val); }
static int64_t quanta_hvec_get_i64(QuantaVecHandle h, size_t index) { return *(int64_t*)quanta_vec_get(h.inner, index); }
static int64_t quanta_hvec_pop_i64(QuantaVecHandle h) {
    if (h.inner->len == 0) return 0;
    h.inner->len--;
    return *(int64_t*)((char*)h.inner->ptr + h.inner->len * h.inner->elem_size);
}

// --- Format string helpers (returns QuantaString) ---

static QuantaString quanta_format_i32(const char* fmt, int32_t v) {
    char buf[64];
    int n = snprintf(buf, sizeof(buf), fmt, v);
    char* heap = (char*)malloc(n + 1);
    memcpy(heap, buf, n + 1);
    QuantaString qs; qs.ptr = heap; qs.len = n; qs.cap = n + 1;
    return qs;
}

static QuantaString quanta_format_f64(const char* fmt, double v) {
    char buf[128];
    int n = snprintf(buf, sizeof(buf), fmt, v);
    char* heap = (char*)malloc(n + 1);
    memcpy(heap, buf, n + 1);
    QuantaString qs; qs.ptr = heap; qs.len = n; qs.cap = n + 1;
    return qs;
}

static QuantaString quanta_format_str(const char* fmt, const char* v) {
    int n = snprintf(NULL, 0, fmt, v);
    char* heap = (char*)malloc(n + 1);
    snprintf(heap, n + 1, fmt, v);
    QuantaString qs; qs.ptr = heap; qs.len = n; qs.cap = n + 1;
    return qs;
}

static QuantaString quanta_i32_to_string(int32_t v) { return quanta_format_i32("%d", v); }
static QuantaString quanta_f64_to_string(double v) { return quanta_format_f64("%g", v); }

// --- Math constants ---
static const double QUANTA_PI = 3.14159265358979323846;
static const double QUANTA_E = 2.71828182845904523536;
static const double QUANTA_TAU = 6.28318530717958647692;

// --- HashMap (i32 -> i32, open addressing with linear probing) ---

typedef struct {
    int32_t* keys;
    int32_t* values;
    uint8_t* occupied;
    size_t cap;
    size_t len;
} QuantaHashMap;

typedef struct { QuantaHashMap* inner; } QuantaMapHandle;

static QuantaMapHandle quanta_map_new(void) {
    QuantaMapHandle h;
    h.inner = (QuantaHashMap*)malloc(sizeof(QuantaHashMap));
    h.inner->cap = 16;
    h.inner->len = 0;
    h.inner->keys = (int32_t*)calloc(16, sizeof(int32_t));
    h.inner->values = (int32_t*)calloc(16, sizeof(int32_t));
    h.inner->occupied = (uint8_t*)calloc(16, sizeof(uint8_t));
    return h;
}

static void quanta_map_grow(QuantaHashMap* m) {
    size_t old_cap = m->cap;
    int32_t* old_keys = m->keys;
    int32_t* old_values = m->values;
    uint8_t* old_occ = m->occupied;
    m->cap *= 2;
    m->len = 0;
    m->keys = (int32_t*)calloc(m->cap, sizeof(int32_t));
    m->values = (int32_t*)calloc(m->cap, sizeof(int32_t));
    m->occupied = (uint8_t*)calloc(m->cap, sizeof(uint8_t));
    for (size_t i = 0; i < old_cap; i++) {
        if (old_occ[i]) {
            uint32_t h = (uint32_t)old_keys[i] * 2654435761u;
            size_t idx = h % m->cap;
            while (m->occupied[idx]) idx = (idx + 1) % m->cap;
            m->keys[idx] = old_keys[i];
            m->values[idx] = old_values[i];
            m->occupied[idx] = 1;
            m->len++;
        }
    }
    free(old_keys); free(old_values); free(old_occ);
}

static void quanta_map_insert(QuantaMapHandle h, int32_t key, int32_t value) {
    QuantaHashMap* m = h.inner;
    if (m->len * 4 >= m->cap * 3) quanta_map_grow(m);
    uint32_t hash = (uint32_t)key * 2654435761u;
    size_t idx = hash % m->cap;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) { m->values[idx] = value; return; }
        idx = (idx + 1) % m->cap;
    }
    m->keys[idx] = key;
    m->values[idx] = value;
    m->occupied[idx] = 1;
    m->len++;
}

static int32_t quanta_map_get(QuantaMapHandle h, int32_t key, int32_t fallback) {
    QuantaHashMap* m = h.inner;
    uint32_t hash = (uint32_t)key * 2654435761u;
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) return m->values[idx];
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return fallback;
}

static bool quanta_map_contains(QuantaMapHandle h, int32_t key) {
    QuantaHashMap* m = h.inner;
    uint32_t hash = (uint32_t)key * 2654435761u;
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) return true;
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return false;
}

static size_t quanta_map_len(QuantaMapHandle h) { return h.inner->len; }

static bool quanta_map_remove(QuantaMapHandle h, int32_t key) {
    QuantaHashMap* m = h.inner;
    uint32_t hash = (uint32_t)key * 2654435761u;
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) {
            m->occupied[idx] = 0;
            m->len--;
            return true;
        }
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return false;
}

// --- Typed HashMap: string key -> f64 value (open addressing, linear probing) ---

typedef struct {
    char** keys;       // heap-allocated copies of key strings
    double* values;
    uint8_t* occupied;
    size_t cap;
    size_t len;
} QuantaStrF64Map;

typedef struct { QuantaStrF64Map* inner; } QuantaStrF64MapHandle;

static uint32_t __quanta_hash_str(const char* s) {
    uint32_t h = 2166136261u;
    for (; *s; s++) { h ^= (uint8_t)*s; h *= 16777619u; }
    return h;
}

static QuantaStrF64MapHandle quanta_hmap_new_str_f64(void) {
    QuantaStrF64MapHandle h;
    h.inner = (QuantaStrF64Map*)malloc(sizeof(QuantaStrF64Map));
    h.inner->cap = 16;
    h.inner->len = 0;
    h.inner->keys = (char**)calloc(16, sizeof(char*));
    h.inner->values = (double*)calloc(16, sizeof(double));
    h.inner->occupied = (uint8_t*)calloc(16, sizeof(uint8_t));
    return h;
}

static void __quanta_hmap_grow_str_f64(QuantaStrF64Map* m) {
    size_t old_cap = m->cap;
    char** old_keys = m->keys;
    double* old_values = m->values;
    uint8_t* old_occ = m->occupied;
    m->cap *= 2;
    m->len = 0;
    m->keys = (char**)calloc(m->cap, sizeof(char*));
    m->values = (double*)calloc(m->cap, sizeof(double));
    m->occupied = (uint8_t*)calloc(m->cap, sizeof(uint8_t));
    for (size_t i = 0; i < old_cap; i++) {
        if (old_occ[i]) {
            uint32_t hash = __quanta_hash_str(old_keys[i]);
            size_t idx = hash % m->cap;
            while (m->occupied[idx]) idx = (idx + 1) % m->cap;
            m->keys[idx] = old_keys[i]; // transfer ownership
            m->values[idx] = old_values[i];
            m->occupied[idx] = 1;
            m->len++;
        }
    }
    free(old_keys); free(old_values); free(old_occ);
}

static void quanta_hmap_insert_str_f64(QuantaStrF64MapHandle h, const char* key, double value) {
    QuantaStrF64Map* m = h.inner;
    if (m->len * 4 >= m->cap * 3) __quanta_hmap_grow_str_f64(m);
    uint32_t hash = __quanta_hash_str(key);
    size_t idx = hash % m->cap;
    while (m->occupied[idx]) {
        if (strcmp(m->keys[idx], key) == 0) { m->values[idx] = value; return; }
        idx = (idx + 1) % m->cap;
    }
    size_t klen = strlen(key);
    m->keys[idx] = (char*)malloc(klen + 1);
    memcpy(m->keys[idx], key, klen + 1);
    m->values[idx] = value;
    m->occupied[idx] = 1;
    m->len++;
}

static double quanta_hmap_get_str_f64(QuantaStrF64MapHandle h, const char* key) {
    QuantaStrF64Map* m = h.inner;
    uint32_t hash = __quanta_hash_str(key);
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (strcmp(m->keys[idx], key) == 0) return m->values[idx];
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return 0.0;
}

static bool quanta_hmap_contains_str_f64(QuantaStrF64MapHandle h, const char* key) {
    QuantaStrF64Map* m = h.inner;
    uint32_t hash = __quanta_hash_str(key);
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (strcmp(m->keys[idx], key) == 0) return true;
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return false;
}

static bool quanta_hmap_remove_str_f64(QuantaStrF64MapHandle h, const char* key) {
    QuantaStrF64Map* m = h.inner;
    uint32_t hash = __quanta_hash_str(key);
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (strcmp(m->keys[idx], key) == 0) {
            free(m->keys[idx]);
            m->keys[idx] = NULL;
            m->occupied[idx] = 0;
            m->len--;
            return true;
        }
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return false;
}

static size_t quanta_hmap_len_str_f64(QuantaStrF64MapHandle h) { return h.inner->len; }

// --- Typed HashMap: i64 key -> f64 value ---

typedef struct {
    int64_t* keys;
    double* values;
    uint8_t* occupied;
    size_t cap;
    size_t len;
} QuantaI64F64Map;

typedef struct { QuantaI64F64Map* inner; } QuantaI64F64MapHandle;

static QuantaI64F64MapHandle quanta_hmap_new_i64_f64(void) {
    QuantaI64F64MapHandle h;
    h.inner = (QuantaI64F64Map*)malloc(sizeof(QuantaI64F64Map));
    h.inner->cap = 16;
    h.inner->len = 0;
    h.inner->keys = (int64_t*)calloc(16, sizeof(int64_t));
    h.inner->values = (double*)calloc(16, sizeof(double));
    h.inner->occupied = (uint8_t*)calloc(16, sizeof(uint8_t));
    return h;
}

static void __quanta_hmap_grow_i64_f64(QuantaI64F64Map* m) {
    size_t old_cap = m->cap;
    int64_t* old_keys = m->keys;
    double* old_values = m->values;
    uint8_t* old_occ = m->occupied;
    m->cap *= 2;
    m->len = 0;
    m->keys = (int64_t*)calloc(m->cap, sizeof(int64_t));
    m->values = (double*)calloc(m->cap, sizeof(double));
    m->occupied = (uint8_t*)calloc(m->cap, sizeof(uint8_t));
    for (size_t i = 0; i < old_cap; i++) {
        if (old_occ[i]) {
            uint32_t hash = (uint32_t)((uint64_t)old_keys[i] * 2654435761u);
            size_t idx = hash % m->cap;
            while (m->occupied[idx]) idx = (idx + 1) % m->cap;
            m->keys[idx] = old_keys[i];
            m->values[idx] = old_values[i];
            m->occupied[idx] = 1;
            m->len++;
        }
    }
    free(old_keys); free(old_values); free(old_occ);
}

static void quanta_hmap_insert_i64_f64(QuantaI64F64MapHandle h, int64_t key, double value) {
    QuantaI64F64Map* m = h.inner;
    if (m->len * 4 >= m->cap * 3) __quanta_hmap_grow_i64_f64(m);
    uint32_t hash = (uint32_t)((uint64_t)key * 2654435761u);
    size_t idx = hash % m->cap;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) { m->values[idx] = value; return; }
        idx = (idx + 1) % m->cap;
    }
    m->keys[idx] = key;
    m->values[idx] = value;
    m->occupied[idx] = 1;
    m->len++;
}

static double quanta_hmap_get_i64_f64(QuantaI64F64MapHandle h, int64_t key) {
    QuantaI64F64Map* m = h.inner;
    uint32_t hash = (uint32_t)((uint64_t)key * 2654435761u);
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) return m->values[idx];
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return 0.0;
}

static bool quanta_hmap_contains_i64_f64(QuantaI64F64MapHandle h, int64_t key) {
    QuantaI64F64Map* m = h.inner;
    uint32_t hash = (uint32_t)((uint64_t)key * 2654435761u);
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) return true;
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return false;
}

static bool quanta_hmap_remove_i64_f64(QuantaI64F64MapHandle h, int64_t key) {
    QuantaI64F64Map* m = h.inner;
    uint32_t hash = (uint32_t)((uint64_t)key * 2654435761u);
    size_t idx = hash % m->cap;
    size_t start = idx;
    while (m->occupied[idx]) {
        if (m->keys[idx] == key) {
            m->occupied[idx] = 0;
            m->len--;
            return true;
        }
        idx = (idx + 1) % m->cap;
        if (idx == start) break;
    }
    return false;
}

static size_t quanta_hmap_len_i64_f64(QuantaI64F64MapHandle h) { return h.inner->len; }

// --- Print formatting helpers ---
// Use snprintf + __quanta_write for reliable output under MinTTY/git-bash.

static void quanta_print_i32(int32_t v) { printf("%d", v); }
static void quanta_print_i64(int64_t v) { printf("%lld", (long long)v); }
static void quanta_print_f32(float v) { printf("%g", (double)v); }
static void quanta_print_f64(double v) { printf("%g", v); }
static void quanta_print_bool(bool v) { printf("%s", v ? "true" : "false"); }
static void quanta_print_str(const char* v) { printf("%s", v); }
static void quanta_print_string(QuantaString v) { printf("%.*s", (int)v.len, v.ptr); }
static void quanta_print_char(char v) { printf("%c", v); }

// --- Math built-in helpers ---

static int32_t quanta_min_i32(int32_t a, int32_t b) { return a < b ? a : b; }
static int32_t quanta_max_i32(int32_t a, int32_t b) { return a > b ? a : b; }
static int64_t quanta_min_i64(int64_t a, int64_t b) { return a < b ? a : b; }
static int64_t quanta_max_i64(int64_t a, int64_t b) { return a > b ? a : b; }
static double quanta_min_f64(double a, double b) { return a < b ? a : b; }
static double quanta_max_f64(double a, double b) { return a > b ? a : b; }
static float quanta_min_f32(float a, float b) { return a < b ? a : b; }
static float quanta_max_f32(float a, float b) { return a > b ? a : b; }

// --- Vector Math Types ---

typedef struct { double x, y; } quanta_vec2;
typedef struct { double x, y, z; } quanta_vec3;
typedef struct { double x, y, z, w; } quanta_vec4;
typedef struct { double m[4][4]; } quanta_mat4;

// Constructors
static quanta_vec2 quanta_vec2_new(double x, double y) { return (quanta_vec2){x, y}; }
static quanta_vec3 quanta_vec3_new(double x, double y, double z) { return (quanta_vec3){x, y, z}; }
static quanta_vec4 quanta_vec4_new(double x, double y, double z, double w) { return (quanta_vec4){x, y, z, w}; }

// Vector dot product
static double quanta_dot2(quanta_vec2 a, quanta_vec2 b) { return a.x*b.x + a.y*b.y; }
static double quanta_dot3(quanta_vec3 a, quanta_vec3 b) { return a.x*b.x + a.y*b.y + a.z*b.z; }
static double quanta_dot4(quanta_vec4 a, quanta_vec4 b) { return a.x*b.x + a.y*b.y + a.z*b.z + a.w*b.w; }

// Vector length
static double quanta_length2(quanta_vec2 v) { return sqrt(quanta_dot2(v, v)); }
static double quanta_length3(quanta_vec3 v) { return sqrt(quanta_dot3(v, v)); }
static double quanta_length4(quanta_vec4 v) { return sqrt(quanta_dot4(v, v)); }

// Vector normalize
static quanta_vec2 quanta_normalize2(quanta_vec2 v) { double l = quanta_length2(v); return (quanta_vec2){v.x/l, v.y/l}; }
static quanta_vec3 quanta_normalize3(quanta_vec3 v) { double l = quanta_length3(v); return (quanta_vec3){v.x/l, v.y/l, v.z/l}; }
static quanta_vec4 quanta_normalize4(quanta_vec4 v) { double l = quanta_length4(v); return (quanta_vec4){v.x/l, v.y/l, v.z/l, v.w/l}; }

// Cross product (vec3 only)
static quanta_vec3 quanta_cross(quanta_vec3 a, quanta_vec3 b) {
    return (quanta_vec3){a.y*b.z - a.z*b.y, a.z*b.x - a.x*b.z, a.x*b.y - a.y*b.x};
}

// Reflect
static quanta_vec3 quanta_reflect3(quanta_vec3 v, quanta_vec3 n) {
    double d = quanta_dot3(v, n);
    return (quanta_vec3){v.x - 2.0*d*n.x, v.y - 2.0*d*n.y, v.z - 2.0*d*n.z};
}

// Lerp
static quanta_vec2 quanta_lerp2(quanta_vec2 a, quanta_vec2 b, double t) {
    return (quanta_vec2){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t};
}
static quanta_vec3 quanta_lerp3(quanta_vec3 a, quanta_vec3 b, double t) {
    return (quanta_vec3){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t, a.z + (b.z-a.z)*t};
}
static quanta_vec4 quanta_lerp4(quanta_vec4 a, quanta_vec4 b, double t) {
    return (quanta_vec4){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t, a.z + (b.z-a.z)*t, a.w + (b.w-a.w)*t};
}

// Vec2 arithmetic
static quanta_vec2 quanta_vec2_add(quanta_vec2 a, quanta_vec2 b) { return (quanta_vec2){a.x+b.x, a.y+b.y}; }
static quanta_vec2 quanta_vec2_sub(quanta_vec2 a, quanta_vec2 b) { return (quanta_vec2){a.x-b.x, a.y-b.y}; }
static quanta_vec2 quanta_vec2_mul(quanta_vec2 a, quanta_vec2 b) { return (quanta_vec2){a.x*b.x, a.y*b.y}; }
static quanta_vec2 quanta_vec2_scale(quanta_vec2 v, double s) { return (quanta_vec2){v.x*s, v.y*s}; }
static quanta_vec2 quanta_vec2_neg(quanta_vec2 v) { return (quanta_vec2){-v.x, -v.y}; }

// Vec3 arithmetic
static quanta_vec3 quanta_vec3_add(quanta_vec3 a, quanta_vec3 b) { return (quanta_vec3){a.x+b.x, a.y+b.y, a.z+b.z}; }
static quanta_vec3 quanta_vec3_sub(quanta_vec3 a, quanta_vec3 b) { return (quanta_vec3){a.x-b.x, a.y-b.y, a.z-b.z}; }
static quanta_vec3 quanta_vec3_mul(quanta_vec3 a, quanta_vec3 b) { return (quanta_vec3){a.x*b.x, a.y*b.y, a.z*b.z}; }
static quanta_vec3 quanta_vec3_scale(quanta_vec3 v, double s) { return (quanta_vec3){v.x*s, v.y*s, v.z*s}; }
static quanta_vec3 quanta_vec3_neg(quanta_vec3 v) { return (quanta_vec3){-v.x, -v.y, -v.z}; }

// Vec4 arithmetic
static quanta_vec4 quanta_vec4_add(quanta_vec4 a, quanta_vec4 b) { return (quanta_vec4){a.x+b.x, a.y+b.y, a.z+b.z, a.w+b.w}; }
static quanta_vec4 quanta_vec4_sub(quanta_vec4 a, quanta_vec4 b) { return (quanta_vec4){a.x-b.x, a.y-b.y, a.z-b.z, a.w-b.w}; }
static quanta_vec4 quanta_vec4_mul(quanta_vec4 a, quanta_vec4 b) { return (quanta_vec4){a.x*b.x, a.y*b.y, a.z*b.z, a.w*b.w}; }
static quanta_vec4 quanta_vec4_scale(quanta_vec4 v, double s) { return (quanta_vec4){v.x*s, v.y*s, v.z*s, v.w*s}; }
static quanta_vec4 quanta_vec4_neg(quanta_vec4 v) { return (quanta_vec4){-v.x, -v.y, -v.z, -v.w}; }

// --- Mat4 operations ---

static quanta_mat4 quanta_mat4_identity(void) {
    quanta_mat4 m = {{{1,0,0,0},{0,1,0,0},{0,0,1,0},{0,0,0,1}}};
    return m;
}

static quanta_mat4 quanta_mat4_mul(quanta_mat4 a, quanta_mat4 b) {
    quanta_mat4 r = {{{0}}};
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            for (int k = 0; k < 4; k++)
                r.m[i][j] += a.m[i][k] * b.m[k][j];
    return r;
}

static quanta_vec4 quanta_mat4_mul_vec4(quanta_mat4 m, quanta_vec4 v) {
    return (quanta_vec4){
        m.m[0][0]*v.x + m.m[0][1]*v.y + m.m[0][2]*v.z + m.m[0][3]*v.w,
        m.m[1][0]*v.x + m.m[1][1]*v.y + m.m[1][2]*v.z + m.m[1][3]*v.w,
        m.m[2][0]*v.x + m.m[2][1]*v.y + m.m[2][2]*v.z + m.m[2][3]*v.w,
        m.m[3][0]*v.x + m.m[3][1]*v.y + m.m[3][2]*v.z + m.m[3][3]*v.w
    };
}

static quanta_mat4 quanta_mat4_translate(quanta_vec3 t) {
    quanta_mat4 m = quanta_mat4_identity();
    m.m[0][3] = t.x; m.m[1][3] = t.y; m.m[2][3] = t.z;
    return m;
}

static quanta_mat4 quanta_mat4_scale(quanta_vec3 s) {
    quanta_mat4 m = {{{s.x,0,0,0},{0,s.y,0,0},{0,0,s.z,0},{0,0,0,1}}};
    return m;
}

static quanta_mat4 quanta_mat4_perspective(double fov, double aspect, double near_val, double far_val) {
    double f = 1.0 / tan(fov * 0.5);
    quanta_mat4 m = {{{0}}};
    m.m[0][0] = f / aspect;
    m.m[1][1] = f;
    m.m[2][2] = (far_val + near_val) / (near_val - far_val);
    m.m[2][3] = (2.0 * far_val * near_val) / (near_val - far_val);
    m.m[3][2] = -1.0;
    return m;
}

// --- Shader math functions ---

static double quanta_clampf(double x, double lo, double hi) { return x < lo ? lo : (x > hi ? hi : x); }
static quanta_vec3 quanta_clamp3(quanta_vec3 v, double lo, double hi) {
    return (quanta_vec3){quanta_clampf(v.x, lo, hi), quanta_clampf(v.y, lo, hi), quanta_clampf(v.z, lo, hi)};
}
static double quanta_smoothstep(double edge0, double edge1, double x) {
    double t = quanta_clampf((x - edge0) / (edge1 - edge0), 0.0, 1.0);
    return t * t * (3.0 - 2.0 * t);
}
static double quanta_mix(double a, double b, double t) { return a + (b - a) * t; }
static double quanta_fract(double x) { return x - floor(x); }
static double quanta_step(double edge, double x) { return x < edge ? 0.0 : 1.0; }
static double quanta_saturate(double x) { return x < 0.0 ? 0.0 : (x > 1.0 ? 1.0 : x); }

// --- Effect handler runtime (setjmp/longjmp based) ---

#include <setjmp.h>

// Effect handler stack
typedef struct QuantaHandler {
    jmp_buf env;
    int32_t effect_id;
    void* handler_data;
    struct QuantaHandler* parent;
} QuantaHandler;

// Global handler stack
static QuantaHandler* __quanta_handler_stack = NULL;

// Push a handler onto the stack
static void quanta_push_handler(QuantaHandler* h, int32_t effect_id) {
    h->effect_id = effect_id;
    h->handler_data = NULL;
    h->parent = __quanta_handler_stack;
    __quanta_handler_stack = h;
}

// Pop a handler from the stack
static void quanta_pop_handler(void) {
    if (__quanta_handler_stack) {
        __quanta_handler_stack = __quanta_handler_stack->parent;
    }
}

// Perform an effect operation — jumps to the nearest handler
static void quanta_perform(int32_t effect_id, int32_t op_id, void* arg, void* result) {
    QuantaHandler* h = __quanta_handler_stack;
    while (h) {
        if (h->effect_id == effect_id) {
            h->handler_data = arg;
            longjmp(h->env, op_id + 1); // +1 because setjmp returns 0 on first call
        }
        h = h->parent;
    }
    // Unhandled effect — abort
    fprintf(stderr, "Unhandled effect %d operation %d\n", effect_id, op_id);
    abort();
}

// --- File I/O ---

static QuantaString quanta_read_file(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return quanta_string_new("");
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    QuantaString qs;
    qs.ptr = buf;
    qs.len = (size_t)len;
    qs.cap = (size_t)(len + 1);
    return qs;
}

static bool quanta_write_file(const char* path, const char* content) {
    FILE* f = fopen(path, "wb");
    if (!f) return false;
    size_t len = strlen(content);
    size_t written = fwrite(content, 1, len, f);
    fclose(f);
    return written == len;
}

static bool quanta_file_exists(const char* path) {
    FILE* f = fopen(path, "rb");
    if (f) { fclose(f); return true; }
    return false;
}

// --- Process / Environment ---

static int32_t quanta_exit(int32_t code) {
    exit(code);
    return code; // unreachable
}

// --- Graphics Stub (Vulkan helper) ---
// Minimal stub that prints what a real Vulkan backend would do.
// Used for testing the FFI integration pattern.
// When connected to a real Vulkan backend, these are replaced by
// linking against vulkan_helper.c / the Vulkan SDK.

typedef struct {
    int32_t initialized;
    int32_t width;
    int32_t height;
    int32_t frame_count;
    int32_t should_close;
} QuantaGfxContext;

static QuantaGfxContext __quanta_gfx_ctx = {0, 0, 0, 0, 0};

static int32_t quanta_gfx_init(int32_t width, int32_t height, const char* title) {
    printf("[GFX] Initializing %dx%d window: %s\n", width, height, title);
    __quanta_gfx_ctx.initialized = 1;
    __quanta_gfx_ctx.width = width;
    __quanta_gfx_ctx.height = height;
    __quanta_gfx_ctx.frame_count = 0;
    __quanta_gfx_ctx.should_close = 0;
    printf("[GFX] Vulkan instance created\n");
    printf("[GFX] Physical device selected\n");
    printf("[GFX] Logical device created\n");
    printf("[GFX] Swapchain created (%dx%d)\n", width, height);
    return 1;
}

static int32_t quanta_gfx_load_shader(const char* path, int32_t stage) {
    printf("[GFX] Loading shader: %s (stage=%s)\n", path, stage == 0 ? "vertex" : "fragment");
    return 1;
}

static int32_t quanta_gfx_create_pipeline(int32_t vertex_shader, int32_t fragment_shader) {
    printf("[GFX] Creating graphics pipeline (vs=%d, fs=%d)\n", vertex_shader, fragment_shader);
    return 1;
}

static void quanta_gfx_begin_frame(void) {
    __quanta_gfx_ctx.frame_count++;
    if (__quanta_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Begin frame %d\n", __quanta_gfx_ctx.frame_count);
    }
}

static void quanta_gfx_clear(float r, float g, float b, float a) {
    if (__quanta_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Clear (%.1f, %.1f, %.1f, %.1f)\n", r, g, b, a);
    }
}

static void quanta_gfx_draw(int32_t vertex_count) {
    if (__quanta_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Draw %d vertices\n", vertex_count);
    }
}

static void quanta_gfx_end_frame(void) {
    if (__quanta_gfx_ctx.frame_count <= 3) {
        printf("[GFX] End frame %d\n", __quanta_gfx_ctx.frame_count);
    }
    if (__quanta_gfx_ctx.frame_count >= 3) {
        __quanta_gfx_ctx.should_close = 1;
    }
}

static int32_t quanta_gfx_should_close(void) {
    return __quanta_gfx_ctx.should_close;
}

static void quanta_gfx_shutdown(void) {
    printf("[GFX] Shutdown complete (%d frames rendered)\n", __quanta_gfx_ctx.frame_count);
    __quanta_gfx_ctx.initialized = 0;
}

// --- String method helpers ---

static bool quanta_string_is_empty(QuantaString s) {
    return s.len == 0;
}

static bool quanta_string_starts_with(QuantaString s, QuantaString prefix) {
    if (prefix.len > s.len) return false;
    return memcmp(s.ptr, prefix.ptr, prefix.len) == 0;
}

static bool quanta_string_ends_with(QuantaString s, QuantaString suffix) {
    if (suffix.len > s.len) return false;
    return memcmp(s.ptr + s.len - suffix.len, suffix.ptr, suffix.len) == 0;
}

static bool quanta_string_contains(QuantaString s, QuantaString substr) {
    if (substr.len == 0) return true;
    if (substr.len > s.len) return false;
    for (size_t i = 0; i <= s.len - substr.len; i++) {
        if (memcmp(s.ptr + i, substr.ptr, substr.len) == 0) return true;
    }
    return false;
}

static QuantaString quanta_string_to_upper(QuantaString s) {
    char* buf = (char*)malloc(s.len + 1);
    for (size_t i = 0; i < s.len; i++) buf[i] = (char)toupper((unsigned char)s.ptr[i]);
    buf[s.len] = '\0';
    QuantaString qs; qs.ptr = buf; qs.len = s.len; qs.cap = s.len + 1;
    return qs;
}

static QuantaString quanta_string_to_lower(QuantaString s) {
    char* buf = (char*)malloc(s.len + 1);
    for (size_t i = 0; i < s.len; i++) buf[i] = (char)tolower((unsigned char)s.ptr[i]);
    buf[s.len] = '\0';
    QuantaString qs; qs.ptr = buf; qs.len = s.len; qs.cap = s.len + 1;
    return qs;
}

static QuantaString quanta_string_trim(QuantaString s) {
    size_t start = 0;
    while (start < s.len && isspace((unsigned char)s.ptr[start])) start++;
    size_t end = s.len;
    while (end > start && isspace((unsigned char)s.ptr[end - 1])) end--;
    size_t new_len = end - start;
    char* buf = (char*)malloc(new_len + 1);
    memcpy(buf, s.ptr + start, new_len);
    buf[new_len] = '\0';
    QuantaString qs; qs.ptr = buf; qs.len = new_len; qs.cap = new_len + 1;
    return qs;
}

static QuantaVec quanta_string_split(QuantaString s, QuantaString delim) {
    QuantaVec v = quanta_vec_new(sizeof(QuantaString));
    if (delim.len == 0) {
        quanta_vec_push(&v, &s);
        return v;
    }
    size_t start = 0;
    for (size_t i = 0; i <= s.len - delim.len; i++) {
        if (memcmp(s.ptr + i, delim.ptr, delim.len) == 0) {
            size_t part_len = i - start;
            char* buf = (char*)malloc(part_len + 1);
            memcpy(buf, s.ptr + start, part_len);
            buf[part_len] = '\0';
            QuantaString part; part.ptr = buf; part.len = part_len; part.cap = part_len + 1;
            quanta_vec_push(&v, &part);
            start = i + delim.len;
            i = start - 1; // loop will increment
        }
    }
    // trailing part
    size_t part_len = s.len - start;
    char* buf = (char*)malloc(part_len + 1);
    memcpy(buf, s.ptr + start, part_len);
    buf[part_len] = '\0';
    QuantaString part; part.ptr = buf; part.len = part_len; part.cap = part_len + 1;
    quanta_vec_push(&v, &part);
    return v;
}

static QuantaVec quanta_string_split_ws(QuantaString s) {
    QuantaVec v = quanta_vec_new(sizeof(QuantaString));
    size_t i = 0;
    while (i < s.len) {
        while (i < s.len && isspace((unsigned char)s.ptr[i])) i++;
        if (i >= s.len) break;
        size_t start = i;
        while (i < s.len && !isspace((unsigned char)s.ptr[i])) i++;
        size_t part_len = i - start;
        char* buf = (char*)malloc(part_len + 1);
        memcpy(buf, s.ptr + start, part_len);
        buf[part_len] = '\0';
        QuantaString part; part.ptr = buf; part.len = part_len; part.cap = part_len + 1;
        quanta_vec_push(&v, &part);
    }
    return v;
}

static QuantaVec quanta_string_lines(QuantaString s) {
    QuantaString delim; delim.ptr = "\n"; delim.len = 1; delim.cap = 0;
    return quanta_string_split(s, delim);
}

// --- stdout initialization ---
// Disable output buffering so printf output is visible immediately,
// especially when running as a child process (e.g., quantac run).
#ifdef _MSC_VER
#pragma section(".CRT$XCU", read)
static void __quanta_init_stdio(void) { setvbuf(stdout, NULL, _IONBF, 0); }
__declspec(allocate(".CRT$XCU")) static void (*__quanta_init_ptr)(void) = __quanta_init_stdio;
#else
__attribute__((constructor)) static void __quanta_init_stdio(void) { setvbuf(stdout, NULL, _IONBF, 0); }
#endif

// ============================================================================
// End QuantaLang Runtime
// ============================================================================

// Type definitions
typedef struct Vec3 {
    double x;
    double y;
    double z;
} Vec3;

typedef struct Mat3 {
    double m[3][3];
} Mat3;

typedef struct RGB {
    double r;
    double g;
    double b;
} RGB;

typedef struct XYZ {
    double x;
    double y;
    double z;
} XYZ;

typedef struct Lab {
    double l;
    double a;
    double b;
} Lab;

// String table
static const char* __str0 = "=== Spectrum Subset: Compiler Feature Validation ===\n";
static const char* __str1 = "\n";
static const char* __str2 = "--- Vec3 Operations ---\n";
static const char* __str3 = "v1.dot(v2) = %g\n";
static const char* __str4 = "v1.length() = %g\n";
static const char* __str5 = "--- Matrix Multiply ---\n";
static const char* __str6 = "identity * (0.5, 0.3, 0.2) = (%g, %g, %g)\n";
static const char* __str7 = "--- sRGB to XYZ Conversion ---\n";
static const char* __str8 = "Linear RGB: (%g, %g, %g)\n";
static const char* __str9 = "XYZ: (%g, %g, %g)\n";
static const char* __str10 = "--- XYZ to Lab Conversion ---\n";
static const char* __str11 = "Lab: (L=%g, a=%g, b=%g)\n";
static const char* __str12 = "Chroma: %g\n";
static const char* __str13 = "--- Full Pipeline: sRGB -> Lab ---\n";
static const char* __str14 = "Lab (direct): (L=%g, a=%g, b=%g)\n";
static const char* __str15 = "--- CIEDE2000 Color Difference ---\n";
static const char* __str16 = "dE(red, green) = %g\n";
static const char* __str17 = "dE(red, blue)  = %g\n";
static const char* __str18 = "dE(red, red)   = %g\n";
static const char* __str19 = "dE76(red, green) = %g\n";
static const char* __str20 = "--- Reinhard Tonemapping ---\n";
static const char* __str21 = "Reinhard(4,2,1) = (%g, %g, %g)\n";
static const char* __str22 = "Reinhard(0.5,0.3,0.2 @ +2EV) = (%g, %g, %g)\n";
static const char* __str23 = "Reinhard_ext(4,2,1, w=6) = (%g, %g, %g)\n";
static const char* __str24 = "--- RGB Methods ---\n";
static const char* __str25 = "Luminance(0.8, 0.4, 0.2) = %g\n";
static const char* __str26 = "Saturate(1.5, -0.3, 0.7) = (%g, %g, %g)\n";
static const char* __str27 = "--- Mat3 x Mat3 ---\n";
static const char* __str28 = "SRGB_TO_XYZ * I [0][0] = %g\n";
static const char* __str29 = "SRGB_TO_XYZ * I [1][1] = %g\n";
static const char* __str30 = "--- Round-trip Validation ---\n";
static const char* __str31 = "Original:    (0.5, 0.3, 0.2)\n";
static const char* __str32 = "Round-trip:  (%g, %g, %g)\n";
static const char* __str33 = "=== All 12 compiler features validated ===\n";

// Global variables
const Mat3 matrices_SRGB_TO_XYZ;
const Mat3 matrices_XYZ_TO_SRGB;

// Forward declarations
static Vec3 Vec3_new(double x, double y, double z);
static double Vec3_dot(Vec3* self, Vec3* other);
static double Vec3_length(Vec3* self);
static Vec3 Vec3_scale(Vec3* self, double s);
static Vec3 Vec3_add(Vec3* self, Vec3* other);
static Vec3 Vec3_sub(Vec3* self, Vec3* other);
static Mat3 Mat3_new(double m[3][3]);
static Mat3 Mat3_identity(void);
static Vec3 Mat3_mul_vec3(Mat3* self, Vec3* v);
static Mat3 Mat3_mul_mat3(Mat3* self, Mat3* other);
static RGB RGB_new(double r, double g, double b);
static RGB RGB_black(void);
static RGB RGB_white(void);
static double RGB_luminance(RGB* self);
static Vec3 RGB_to_vec3(RGB* self);
static RGB RGB_from_vec3(Vec3 v);
static RGB RGB_saturate(RGB* self);
static XYZ XYZ_new(double x, double y, double z);
static XYZ XYZ_d65_white(void);
static Lab Lab_new(double l, double a, double b);
static double Lab_chroma(Lab* self);
static double Lab_hue(Lab* self);
static double transfer_srgb_eotf(double v);
static double transfer_srgb_oetf(double v);
static RGB convert_srgb_to_linear(RGB rgb);
static RGB convert_linear_to_srgb(RGB rgb);
static XYZ convert_srgb_to_xyz(RGB rgb);
static RGB convert_xyz_to_srgb(XYZ xyz);
static Lab convert_xyz_to_lab(XYZ xyz);
static Lab convert_srgb_to_lab(RGB rgb);
static double color_difference_delta_e_76(Lab lab1, Lab lab2);
static double color_difference_delta_e_2000(Lab lab1, Lab lab2, double kl, double kc, double kh);
static RGB tonemap_reinhard(RGB rgb);
static RGB tonemap_reinhard_extended(RGB rgb, double white);
static RGB tonemap_apply_with_exposure(RGB rgb, double exposure);
int32_t main(void);

static Vec3 Vec3_new(double x, double y, double z) {
    Vec3 _ret;
    Vec3 _4;

    _4 = (Vec3){ x, y, z };
    fflush(stdout);
    return _4;
}

static double Vec3_dot(Vec3* self, Vec3* other) {
    double _ret;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;

    _3 = self->x;
    _4 = other->x;
    _5 = (_3 * _4);
    _6 = self->y;
    _7 = other->y;
    _8 = (_6 * _7);
    _9 = (_5 + _8);
    _10 = self->z;
    _11 = other->z;
    _12 = (_10 * _11);
    _13 = (_9 + _12);
    fflush(stdout);
    return _13;
}

static double Vec3_length(Vec3* self) {
    double _ret;
    double _2;
    double _3;

    _2 = Vec3_dot(self, self);
    goto bb1;
bb1:
    _3 = sqrt(_2);
    goto bb2;
bb2:
    fflush(stdout);
    return _3;
}

static Vec3 Vec3_scale(Vec3* self, double s) {
    Vec3 _ret;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    Vec3 _9;

    _3 = self->x;
    _4 = (_3 * s);
    _5 = self->y;
    _6 = (_5 * s);
    _7 = self->z;
    _8 = (_7 * s);
    _9 = Vec3_new(_4, _6, _8);
    goto bb1;
bb1:
    fflush(stdout);
    return _9;
}

static Vec3 Vec3_add(Vec3* self, Vec3* other) {
    Vec3 _ret;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    Vec3 _12;

    _3 = self->x;
    _4 = other->x;
    _5 = (_3 + _4);
    _6 = self->y;
    _7 = other->y;
    _8 = (_6 + _7);
    _9 = self->z;
    _10 = other->z;
    _11 = (_9 + _10);
    _12 = Vec3_new(_5, _8, _11);
    goto bb1;
bb1:
    fflush(stdout);
    return _12;
}

static Vec3 Vec3_sub(Vec3* self, Vec3* other) {
    Vec3 _ret;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    Vec3 _12;

    _3 = self->x;
    _4 = other->x;
    _5 = (_3 - _4);
    _6 = self->y;
    _7 = other->y;
    _8 = (_6 - _7);
    _9 = self->z;
    _10 = other->z;
    _11 = (_9 - _10);
    _12 = Vec3_new(_5, _8, _11);
    goto bb1;
bb1:
    fflush(stdout);
    return _12;
}

static Mat3 Mat3_new(double m[3][3]) {
    Mat3 _ret;
    Mat3 _2;

    _2 = (Mat3){ m };
    fflush(stdout);
    return _2;
}

static Mat3 Mat3_identity(void) {
    Mat3 _ret;
    double _1[3];
    double _2[3];
    double _3[3];
    double _4[3][3];
    Mat3 _5;

    _1[0] = 1;
    _1[1] = 0;
    _1[2] = 0;
    _2[0] = 0;
    _2[1] = 1;
    _2[2] = 0;
    _3[0] = 0;
    _3[1] = 0;
    _3[2] = 1;
    _4[0] = _1;
    _4[1] = _2;
    _4[2] = _3;
    _5 = Mat3_new(_4);
    goto bb1;
bb1:
    fflush(stdout);
    return _5;
}

static Vec3 Mat3_mul_vec3(Mat3* self, Vec3* v) {
    Vec3 _ret;
    double _3[3][3];
    double _4[3];
    double _5;
    double _6;
    double _7;
    double _8[3][3];
    double _9[3];
    double _10;
    double _11;
    double _12;
    double _13;
    double _14[3][3];
    double _15[3];
    double _16;
    double _17;
    double _18;
    double _19;
    double _20[3][3];
    double _21[3];
    double _22;
    double _23;
    double _24;
    double _25[3][3];
    double _26[3];
    double _27;
    double _28;
    double _29;
    double _30;
    double _31[3][3];
    double _32[3];
    double _33;
    double _34;
    double _35;
    double _36;
    double _37[3][3];
    double _38[3];
    double _39;
    double _40;
    double _41;
    double _42[3][3];
    double _43[3];
    double _44;
    double _45;
    double _46;
    double _47;
    double _48[3][3];
    double _49[3];
    double _50;
    double _51;
    double _52;
    double _53;
    Vec3 _54;

    memcpy(_3, &(self->m), sizeof(_3));
    memcpy(_4, &(_3[0]), sizeof(_4));
    _5 = _4[0];
    _6 = v->x;
    _7 = (_5 * _6);
    memcpy(_8, &(self->m), sizeof(_8));
    memcpy(_9, &(_8[0]), sizeof(_9));
    _10 = _9[1];
    _11 = v->y;
    _12 = (_10 * _11);
    _13 = (_7 + _12);
    memcpy(_14, &(self->m), sizeof(_14));
    memcpy(_15, &(_14[0]), sizeof(_15));
    _16 = _15[2];
    _17 = v->z;
    _18 = (_16 * _17);
    _19 = (_13 + _18);
    memcpy(_20, &(self->m), sizeof(_20));
    memcpy(_21, &(_20[1]), sizeof(_21));
    _22 = _21[0];
    _23 = v->x;
    _24 = (_22 * _23);
    memcpy(_25, &(self->m), sizeof(_25));
    memcpy(_26, &(_25[1]), sizeof(_26));
    _27 = _26[1];
    _28 = v->y;
    _29 = (_27 * _28);
    _30 = (_24 + _29);
    memcpy(_31, &(self->m), sizeof(_31));
    memcpy(_32, &(_31[1]), sizeof(_32));
    _33 = _32[2];
    _34 = v->z;
    _35 = (_33 * _34);
    _36 = (_30 + _35);
    memcpy(_37, &(self->m), sizeof(_37));
    memcpy(_38, &(_37[2]), sizeof(_38));
    _39 = _38[0];
    _40 = v->x;
    _41 = (_39 * _40);
    memcpy(_42, &(self->m), sizeof(_42));
    memcpy(_43, &(_42[2]), sizeof(_43));
    _44 = _43[1];
    _45 = v->y;
    _46 = (_44 * _45);
    _47 = (_41 + _46);
    memcpy(_48, &(self->m), sizeof(_48));
    memcpy(_49, &(_48[2]), sizeof(_49));
    _50 = _49[2];
    _51 = v->z;
    _52 = (_50 * _51);
    _53 = (_47 + _52);
    _54 = Vec3_new(_19, _36, _53);
    goto bb1;
bb1:
    fflush(stdout);
    return _54;
}

static Mat3 Mat3_mul_mat3(Mat3* self, Mat3* other) {
    Mat3 _ret;
    int32_t _4;
    bool _5;
    int32_t _6;
    bool _7;
    int32_t _8;
    bool _9;
    int32_t _10;
    int32_t _11;
    double _12[3][3];
    double _13[3];
    double _14;
    double _15[3][3];
    double _16[3];
    double _17;
    double _18;
    int32_t _19;
    Mat3 _20;

    _4 = 0;
    goto bb1;
bb1:
    _5 = (_4 >= 3);
    if (_5) goto bb4; else goto bb2;
bb2:
    _6 = 0;
    goto bb5;
bb3:
    _4 = (_4 + 1);
    goto bb1;
bb4:
    _20 = Mat3_new(result);
    goto bb13;
bb5:
    _7 = (_6 >= 3);
    if (_7) goto bb8; else goto bb6;
bb6:
    _8 = 0;
    goto bb9;
bb7:
    _6 = (_6 + 1);
    goto bb5;
bb8:
    goto bb3;
bb9:
    _9 = (_8 >= 3);
    if (_9) goto bb12; else goto bb10;
bb10:
    _10 = result[_4];
    _11 = _10[_6];
    memcpy(_12, &(self->m), sizeof(_12));
    memcpy(_13, &(_12[_4]), sizeof(_13));
    _14 = _13[_8];
    memcpy(_15, &(other->m), sizeof(_15));
    memcpy(_16, &(_15[_8]), sizeof(_16));
    _17 = _16[_6];
    _18 = (_14 * _17);
    _19 = (_11 + _18);
    goto bb11;
bb11:
    _8 = (_8 + 1);
    goto bb9;
bb12:
    goto bb7;
bb13:
    fflush(stdout);
    return _20;
}

static RGB RGB_new(double r, double g, double b) {
    RGB _ret;
    RGB _4;

    _4 = (RGB){ r, g, b };
    fflush(stdout);
    return _4;
}

static RGB RGB_black(void) {
    RGB _ret;
    RGB _1;

    _1 = RGB_new(0, 0, 0);
    goto bb1;
bb1:
    fflush(stdout);
    return _1;
}

static RGB RGB_white(void) {
    RGB _ret;
    RGB _1;

    _1 = RGB_new(1, 1, 1);
    goto bb1;
bb1:
    fflush(stdout);
    return _1;
}

static double RGB_luminance(RGB* self) {
    double _ret;
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;

    _2 = self->r;
    _3 = (0.2126 * _2);
    _4 = self->g;
    _5 = (0.7152 * _4);
    _6 = (_3 + _5);
    _7 = self->b;
    _8 = (0.0722 * _7);
    _9 = (_6 + _8);
    fflush(stdout);
    return _9;
}

static Vec3 RGB_to_vec3(RGB* self) {
    Vec3 _ret;
    double _2;
    double _3;
    double _4;
    Vec3 _5;

    _2 = self->r;
    _3 = self->g;
    _4 = self->b;
    _5 = Vec3_new(_2, _3, _4);
    goto bb1;
bb1:
    fflush(stdout);
    return _5;
}

static RGB RGB_from_vec3(Vec3 v) {
    RGB _ret;
    double _2;
    double _3;
    double _4;
    RGB _5;

    _2 = v.x;
    _3 = v.y;
    _4 = v.z;
    _5 = RGB_new(_2, _3, _4);
    goto bb1;
bb1:
    fflush(stdout);
    return _5;
}

static RGB RGB_saturate(RGB* self) {
    RGB _ret;
    double _2;
    bool _3;
    double _4;
    double _5;
    bool _6;
    double _7;
    double _8;
    double r;
    double _10;
    bool _11;
    double _12;
    double _13;
    bool _14;
    double _15;
    double _16;
    double g;
    double _18;
    bool _19;
    double _20;
    double _21;
    bool _22;
    double _23;
    double _24;
    double b;
    RGB _26;

    _2 = self->r;
    _3 = (_2 < 0);
    if (_3) goto bb1; else goto bb2;
bb1:
    _4 = 0;
    goto bb3;
bb2:
    _5 = self->r;
    _6 = (_5 > 1);
    if (_6) goto bb4; else goto bb5;
bb3:
    r = _4;
    _10 = self->g;
    _11 = (_10 < 0);
    if (_11) goto bb7; else goto bb8;
bb4:
    _7 = 1;
    goto bb6;
bb5:
    _8 = self->r;
    _7 = _8;
    goto bb6;
bb6:
    _4 = _7;
    goto bb3;
bb7:
    _12 = 0;
    goto bb9;
bb8:
    _13 = self->g;
    _14 = (_13 > 1);
    if (_14) goto bb10; else goto bb11;
bb9:
    g = _12;
    _18 = self->b;
    _19 = (_18 < 0);
    if (_19) goto bb13; else goto bb14;
bb10:
    _15 = 1;
    goto bb12;
bb11:
    _16 = self->g;
    _15 = _16;
    goto bb12;
bb12:
    _12 = _15;
    goto bb9;
bb13:
    _20 = 0;
    goto bb15;
bb14:
    _21 = self->b;
    _22 = (_21 > 1);
    if (_22) goto bb16; else goto bb17;
bb15:
    b = _20;
    _26 = RGB_new(r, g, b);
    goto bb19;
bb16:
    _23 = 1;
    goto bb18;
bb17:
    _24 = self->b;
    _23 = _24;
    goto bb18;
bb18:
    _20 = _23;
    goto bb15;
bb19:
    fflush(stdout);
    return _26;
}

static XYZ XYZ_new(double x, double y, double z) {
    XYZ _ret;
    XYZ _4;

    _4 = (XYZ){ x, y, z };
    fflush(stdout);
    return _4;
}

static XYZ XYZ_d65_white(void) {
    XYZ _ret;
    XYZ _1;

    _1 = XYZ_new(0.95047, 1, 1.08883);
    goto bb1;
bb1:
    fflush(stdout);
    return _1;
}

static Lab Lab_new(double l, double a, double b) {
    Lab _ret;
    Lab _4;

    _4 = (Lab){ l, a, b };
    fflush(stdout);
    return _4;
}

static double Lab_chroma(Lab* self) {
    double _ret;
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;

    _2 = self->a;
    _3 = self->a;
    _4 = (_2 * _3);
    _5 = self->b;
    _6 = self->b;
    _7 = (_5 * _6);
    _8 = (_4 + _7);
    _9 = sqrt(_8);
    goto bb1;
bb1:
    fflush(stdout);
    return _9;
}

static double Lab_hue(Lab* self) {
    double _ret;
    double _2;
    double _3;
    int32_t _4;

    _2 = self->b;
    _3 = self->a;
    _4 = atan2(_2, _3);
    goto bb1;
bb1:
    fflush(stdout);
    return _4;
}

static double transfer_srgb_eotf(double v) {
    double _ret;
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;

    _2 = (v <= 0.04045);
    if (_2) goto bb1; else goto bb2;
bb1:
    _3 = (v / 12.92);
    _4 = _3;
    goto bb3;
bb2:
    _5 = (v + 0.055);
    _6 = (_5 / 1.055);
    _7 = pow(_6, 2.4);
    goto bb4;
bb3:
    fflush(stdout);
    return _4;
bb4:
    _4 = _7;
    goto bb3;
}

static double transfer_srgb_oetf(double v) {
    double _ret;
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;

    _2 = (v <= 0.0031308);
    if (_2) goto bb1; else goto bb2;
bb1:
    _3 = (v * 12.92);
    _4 = _3;
    goto bb3;
bb2:
    _5 = (1 / 2.4);
    _6 = pow(v, _5);
    goto bb4;
bb3:
    fflush(stdout);
    return _4;
bb4:
    _7 = (1.055 * _6);
    _8 = (_7 - 0.055);
    _4 = _8;
    goto bb3;
}

static RGB convert_srgb_to_linear(RGB rgb) {
    RGB _ret;
    double _2;
    int32_t _3;
    double _4;
    int32_t _5;
    double _6;
    int32_t _7;
    RGB _8;

    _2 = rgb.r;
    _3 = srgb_eotf(_2);
    goto bb1;
bb1:
    _4 = rgb.g;
    _5 = srgb_eotf(_4);
    goto bb2;
bb2:
    _6 = rgb.b;
    _7 = srgb_eotf(_6);
    goto bb3;
bb3:
    _8 = RGB_new(_3, _5, _7);
    goto bb4;
bb4:
    fflush(stdout);
    return _8;
}

static RGB convert_linear_to_srgb(RGB rgb) {
    RGB _ret;
    double _2;
    int32_t _3;
    double _4;
    int32_t _5;
    double _6;
    int32_t _7;
    RGB _8;

    _2 = rgb.r;
    _3 = srgb_oetf(_2);
    goto bb1;
bb1:
    _4 = rgb.g;
    _5 = srgb_oetf(_4);
    goto bb2;
bb2:
    _6 = rgb.b;
    _7 = srgb_oetf(_6);
    goto bb3;
bb3:
    _8 = RGB_new(_3, _5, _7);
    goto bb4;
bb4:
    fflush(stdout);
    return _8;
}

static XYZ convert_srgb_to_xyz(RGB rgb) {
    XYZ _ret;
    RGB* _2;
    Vec3 _3;
    Vec3* _4;
    int32_t _5;
    int32_t v;
    int32_t _7;
    int32_t _8;
    int32_t _9;
    XYZ _10;

    _2 = &rgb;
    _3 = RGB_to_vec3(_2);
    goto bb1;
bb1:
    _4 = &_3;
    _5 = mul_vec3(SRGB_TO_XYZ, _4);
    goto bb2;
bb2:
    v = _5;
    _7 = v.x;
    _8 = v.y;
    _9 = v.z;
    _10 = XYZ_new(_7, _8, _9);
    goto bb3;
bb3:
    fflush(stdout);
    return _10;
}

static RGB convert_xyz_to_srgb(XYZ xyz) {
    RGB _ret;
    double _2;
    double _3;
    double _4;
    Vec3 _5;
    Vec3* _6;
    int32_t _7;
    int32_t v;
    int32_t _9;
    int32_t _10;
    int32_t _11;
    RGB _12;

    _2 = xyz.x;
    _3 = xyz.y;
    _4 = xyz.z;
    _5 = Vec3_new(_2, _3, _4);
    goto bb1;
bb1:
    _6 = &_5;
    _7 = mul_vec3(XYZ_TO_SRGB, _6);
    goto bb2;
bb2:
    v = _7;
    _9 = v.x;
    _10 = v.y;
    _11 = v.z;
    _12 = RGB_new(_9, _10, _11);
    goto bb3;
bb3:
    fflush(stdout);
    return _12;
}

static Lab convert_xyz_to_lab(XYZ xyz) {
    Lab _ret;
    XYZ _2;
    XYZ white;
    double _4;
    double delta;
    double _6;
    double delta_sq;
    double _8;
    double delta_cu;
    double _10;
    double _11;
    double _12;
    double xr;
    double _14;
    double _15;
    double _16;
    double yr;
    double _18;
    double _19;
    double _20;
    double zr;
    bool _22;
    double _23;
    double _24;
    double _25;
    double _26;
    double _27;
    double _28;
    double _29;
    double fx;
    bool _31;
    double _32;
    double _33;
    double _34;
    double _35;
    double _36;
    double _37;
    double _38;
    double fy;
    bool _40;
    double _41;
    double _42;
    double _43;
    double _44;
    double _45;
    double _46;
    double _47;
    double fz;
    double _49;
    double _50;
    double _51;
    double _52;
    double _53;
    double _54;
    Lab _55;

    _2 = XYZ_d65_white();
    goto bb1;
bb1:
    white = _2;
    _4 = (6 / 29);
    delta = _4;
    _6 = (delta * delta);
    delta_sq = _6;
    _8 = (delta_sq * delta);
    delta_cu = _8;
    _10 = xyz.x;
    _11 = white.x;
    _12 = (_10 / _11);
    xr = _12;
    _14 = xyz.y;
    _15 = white.y;
    _16 = (_14 / _15);
    yr = _16;
    _18 = xyz.z;
    _19 = white.z;
    _20 = (_18 / _19);
    zr = _20;
    _22 = (xr > delta_cu);
    if (_22) goto bb2; else goto bb3;
bb2:
    _23 = (1 / 3);
    _24 = pow(xr, _23);
    goto bb5;
bb3:
    _26 = (3 * delta_sq);
    _27 = (xr / _26);
    _28 = (4 / 29);
    _29 = (_27 + _28);
    _25 = _29;
    goto bb4;
bb4:
    fx = _25;
    _31 = (yr > delta_cu);
    if (_31) goto bb6; else goto bb7;
bb5:
    _25 = _24;
    goto bb4;
bb6:
    _32 = (1 / 3);
    _33 = pow(yr, _32);
    goto bb9;
bb7:
    _35 = (3 * delta_sq);
    _36 = (yr / _35);
    _37 = (4 / 29);
    _38 = (_36 + _37);
    _34 = _38;
    goto bb8;
bb8:
    fy = _34;
    _40 = (zr > delta_cu);
    if (_40) goto bb10; else goto bb11;
bb9:
    _34 = _33;
    goto bb8;
bb10:
    _41 = (1 / 3);
    _42 = pow(zr, _41);
    goto bb13;
bb11:
    _44 = (3 * delta_sq);
    _45 = (zr / _44);
    _46 = (4 / 29);
    _47 = (_45 + _46);
    _43 = _47;
    goto bb12;
bb12:
    fz = _43;
    _49 = (116 * fy);
    _50 = (_49 - 16);
    _51 = (fx - fy);
    _52 = (500 * _51);
    _53 = (fy - fz);
    _54 = (200 * _53);
    _55 = Lab_new(_50, _52, _54);
    goto bb14;
bb13:
    _43 = _42;
    goto bb12;
bb14:
    fflush(stdout);
    return _55;
}

static Lab convert_srgb_to_lab(RGB rgb) {
    Lab _ret;
    int32_t _2;
    int32_t linear;
    int32_t _4;
    int32_t xyz;
    int32_t _6;

    _2 = srgb_to_linear(rgb);
    goto bb1;
bb1:
    linear = _2;
    _4 = srgb_to_xyz(linear);
    goto bb2;
bb2:
    xyz = _4;
    _6 = xyz_to_lab(xyz);
    goto bb3;
bb3:
    fflush(stdout);
    return _6;
}

static double color_difference_delta_e_76(Lab lab1, Lab lab2) {
    double _ret;
    double _3;
    double _4;
    double _5;
    double dl;
    double _7;
    double _8;
    double _9;
    double da;
    double _11;
    double _12;
    double _13;
    double db;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    double _20;

    _3 = lab2.l;
    _4 = lab1.l;
    _5 = (_3 - _4);
    dl = _5;
    _7 = lab2.a;
    _8 = lab1.a;
    _9 = (_7 - _8);
    da = _9;
    _11 = lab2.b;
    _12 = lab1.b;
    _13 = (_11 - _12);
    db = _13;
    _15 = (dl * dl);
    _16 = (da * da);
    _17 = (_15 + _16);
    _18 = (db * db);
    _19 = (_17 + _18);
    _20 = sqrt(_19);
    goto bb1;
bb1:
    fflush(stdout);
    return _20;
}

static double color_difference_delta_e_2000(Lab lab1, Lab lab2, double kl, double kc, double kh) {
    double _ret;
    double pi;
    double _7;
    double l1;
    double _9;
    double a1;
    double _11;
    double b1;
    double _13;
    double l2;
    double _15;
    double a2;
    double _17;
    double b2;
    double _19;
    double _20;
    double _21;
    double _22;
    double c1;
    double _24;
    double _25;
    double _26;
    double _27;
    double c2;
    double _29;
    double _30;
    double c_avg;
    double _32;
    double c_avg_pow7;
    double _34;
    double _35;
    double _36;
    double _37;
    double _38;
    double _39;
    double g;
    double _41;
    double _42;
    double a1_prime;
    double _44;
    double _45;
    double a2_prime;
    double _47;
    double _48;
    double _49;
    double _50;
    double c1_prime;
    double _52;
    double _53;
    double _54;
    double _55;
    double c2_prime;
    bool _57;
    double _58;
    int32_t _59;
    int32_t _60;
    int32_t _61;
    int32_t h_62;
    bool _63;
    int32_t _64;
    int32_t _65;
    double h1_prime;
    bool _67;
    double _68;
    int32_t _69;
    int32_t _70;
    int32_t _71;
    int32_t h_72;
    bool _73;
    int32_t _74;
    int32_t _75;
    double h2_prime;
    double _77;
    double dl_prime;
    double _79;
    double dc_prime;
    double _81;
    bool _82;
    double _83;
    double _84;
    double dh;
    bool _86;
    double _87;
    double _88;
    double _89;
    bool _90;
    double _91;
    double _92;
    double dh_prime;
    double _94;
    double _95;
    double _96;
    double _97;
    double _98;
    double _99;
    double _100;
    double dh_prime_capital;
    double _102;
    double _103;
    double l_avg;
    double _105;
    double _106;
    double c_avg_prime;
    double _108;
    bool _109;
    double _110;
    double _111;
    double _112;
    double _113;
    bool _114;
    double _115;
    double _116;
    double _117;
    double _118;
    bool _119;
    double _120;
    double _121;
    double _122;
    double _123;
    double _124;
    double _125;
    double _126;
    double h_avg_prime;
    double _128;
    double _129;
    double _130;
    double _131;
    double _132;
    double _133;
    double _134;
    double _135;
    double _136;
    double _137;
    double _138;
    double _139;
    double _140;
    double _141;
    double _142;
    double _143;
    double _144;
    double _145;
    double _146;
    double _147;
    double _148;
    double _149;
    double _150;
    double _151;
    double _152;
    double _153;
    double t;
    double _155;
    double _156;
    double _157;
    double l_avg_minus_50_sq;
    double _159;
    double _160;
    double _161;
    double _162;
    double _163;
    double sl;
    double _165;
    double _166;
    double sc;
    double _168;
    double _169;
    double _170;
    double sh;
    double _172;
    double c_avg_prime_pow7;
    double _174;
    double _175;
    double _176;
    double _177;
    double _178;
    double rc;
    double _180;
    double _181;
    double _182;
    double _183;
    int32_t _184;
    double _185;
    double delta_theta;
    double _187;
    double _188;
    double _189;
    double _190;
    double _191;
    double _192;
    double rt;
    double _194;
    double _195;
    double term_l;
    double _197;
    double _198;
    double term_c;
    double _200;
    double _201;
    double term_h;
    double _203;
    double _204;
    double _205;
    double _206;
    double _207;
    double _208;
    double _209;
    double _210;
    double _211;

    pi = 3.141592653589793;
    _7 = lab1.l;
    l1 = _7;
    _9 = lab1.a;
    a1 = _9;
    _11 = lab1.b;
    b1 = _11;
    _13 = lab2.l;
    l2 = _13;
    _15 = lab2.a;
    a2 = _15;
    _17 = lab2.b;
    b2 = _17;
    _19 = (a1 * a1);
    _20 = (b1 * b1);
    _21 = (_19 + _20);
    _22 = sqrt(_21);
    goto bb1;
bb1:
    c1 = _22;
    _24 = (a2 * a2);
    _25 = (b2 * b2);
    _26 = (_24 + _25);
    _27 = sqrt(_26);
    goto bb2;
bb2:
    c2 = _27;
    _29 = (c1 + c2);
    _30 = (_29 / 2);
    c_avg = _30;
    _32 = pow(c_avg, 7);
    goto bb3;
bb3:
    c_avg_pow7 = _32;
    _34 = pow(25, 7);
    goto bb4;
bb4:
    _35 = (c_avg_pow7 + _34);
    _36 = (c_avg_pow7 / _35);
    _37 = sqrt(_36);
    goto bb5;
bb5:
    _38 = (1 - _37);
    _39 = (0.5 * _38);
    g = _39;
    _41 = (1 + g);
    _42 = (a1 * _41);
    a1_prime = _42;
    _44 = (1 + g);
    _45 = (a2 * _44);
    a2_prime = _45;
    _47 = (a1_prime * a1_prime);
    _48 = (b1 * b1);
    _49 = (_47 + _48);
    _50 = sqrt(_49);
    goto bb6;
bb6:
    c1_prime = _50;
    _52 = (a2_prime * a2_prime);
    _53 = (b2 * b2);
    _54 = (_52 + _53);
    _55 = sqrt(_54);
    goto bb7;
bb7:
    c2_prime = _55;
    _57 = (a1_prime == 0);
    if (_57) goto bb8; else goto bb9;
bb8:
    _58 = 0;
    goto bb10;
bb9:
    _59 = atan2(b1, a1_prime);
    goto bb11;
bb10:
    h1_prime = _58;
    _67 = (a2_prime == 0);
    if (_67) goto bb15; else goto bb16;
bb11:
    _60 = (_59 * 180);
    _61 = (_60 / pi);
    h_62 = _61;
    _63 = (h_62 < 0);
    if (_63) goto bb12; else goto bb13;
bb12:
    _64 = (h_62 + 360);
    _65 = _64;
    goto bb14;
bb13:
    _65 = h_62;
    goto bb14;
bb14:
    _58 = _65;
    goto bb10;
bb15:
    _68 = 0;
    goto bb17;
bb16:
    _69 = atan2(b2, a2_prime);
    goto bb18;
bb17:
    h2_prime = _68;
    _77 = (l2 - l1);
    dl_prime = _77;
    _79 = (c2_prime - c1_prime);
    dc_prime = _79;
    _81 = (c1_prime * c2_prime);
    _82 = (_81 == 0);
    if (_82) goto bb22; else goto bb23;
bb18:
    _70 = (_69 * 180);
    _71 = (_70 / pi);
    h_72 = _71;
    _73 = (h_72 < 0);
    if (_73) goto bb19; else goto bb20;
bb19:
    _74 = (h_72 + 360);
    _75 = _74;
    goto bb21;
bb20:
    _75 = h_72;
    goto bb21;
bb21:
    _68 = _75;
    goto bb17;
bb22:
    _83 = 0;
    goto bb24;
bb23:
    _84 = (h2_prime - h1_prime);
    dh = _84;
    _86 = (dh > 180);
    if (_86) goto bb25; else goto bb26;
bb24:
    dh_prime = _83;
    _94 = (c1_prime * c2_prime);
    _95 = sqrt(_94);
    goto bb31;
bb25:
    _87 = (dh - 360);
    _88 = _87;
    goto bb27;
bb26:
    _89 = (-180);
    _90 = (dh < _89);
    if (_90) goto bb28; else goto bb29;
bb27:
    _83 = _88;
    goto bb24;
bb28:
    _91 = (dh + 360);
    _92 = _91;
    goto bb30;
bb29:
    _92 = dh;
    goto bb30;
bb30:
    _88 = _92;
    goto bb27;
bb31:
    _96 = (2 * _95);
    _97 = (dh_prime * pi);
    _98 = (_97 / 360);
    _99 = sin(_98);
    goto bb32;
bb32:
    _100 = (_96 * _99);
    dh_prime_capital = _100;
    _102 = (l1 + l2);
    _103 = (_102 / 2);
    l_avg = _103;
    _105 = (c1_prime + c2_prime);
    _106 = (_105 / 2);
    c_avg_prime = _106;
    _108 = (c1_prime * c2_prime);
    _109 = (_108 == 0);
    if (_109) goto bb33; else goto bb34;
bb33:
    _110 = (h1_prime + h2_prime);
    _111 = _110;
    goto bb35;
bb34:
    _112 = (h1_prime - h2_prime);
    _113 = fabs(_112);
    goto bb36;
bb35:
    h_avg_prime = _111;
    _128 = (h_avg_prime - 30);
    _129 = (_128 * pi);
    _130 = (_129 / 180);
    _131 = cos(_130);
    goto bb43;
bb36:
    _114 = (_113 <= 180);
    if (_114) goto bb37; else goto bb38;
bb37:
    _115 = (h1_prime + h2_prime);
    _116 = (_115 / 2);
    _117 = _116;
    goto bb39;
bb38:
    _118 = (h1_prime + h2_prime);
    _119 = (_118 < 360);
    if (_119) goto bb40; else goto bb41;
bb39:
    _111 = _117;
    goto bb35;
bb40:
    _120 = (h1_prime + h2_prime);
    _121 = (_120 + 360);
    _122 = (_121 / 2);
    _123 = _122;
    goto bb42;
bb41:
    _124 = (h1_prime + h2_prime);
    _125 = (_124 - 360);
    _126 = (_125 / 2);
    _123 = _126;
    goto bb42;
bb42:
    _117 = _123;
    goto bb39;
bb43:
    _132 = (0.17 * _131);
    _133 = (1 - _132);
    _134 = (2 * h_avg_prime);
    _135 = (_134 * pi);
    _136 = (_135 / 180);
    _137 = cos(_136);
    goto bb44;
bb44:
    _138 = (0.24 * _137);
    _139 = (_133 + _138);
    _140 = (3 * h_avg_prime);
    _141 = (_140 + 6);
    _142 = (_141 * pi);
    _143 = (_142 / 180);
    _144 = cos(_143);
    goto bb45;
bb45:
    _145 = (0.32 * _144);
    _146 = (_139 + _145);
    _147 = (4 * h_avg_prime);
    _148 = (_147 - 63);
    _149 = (_148 * pi);
    _150 = (_149 / 180);
    _151 = cos(_150);
    goto bb46;
bb46:
    _152 = (0.2 * _151);
    _153 = (_146 - _152);
    t = _153;
    _155 = (l_avg - 50);
    _156 = (l_avg - 50);
    _157 = (_155 * _156);
    l_avg_minus_50_sq = _157;
    _159 = (0.015 * l_avg_minus_50_sq);
    _160 = (20 + l_avg_minus_50_sq);
    _161 = sqrt(_160);
    goto bb47;
bb47:
    _162 = (_159 / _161);
    _163 = (1 + _162);
    sl = _163;
    _165 = (0.045 * c_avg_prime);
    _166 = (1 + _165);
    sc = _166;
    _168 = (0.015 * c_avg_prime);
    _169 = (_168 * t);
    _170 = (1 + _169);
    sh = _170;
    _172 = pow(c_avg_prime, 7);
    goto bb48;
bb48:
    c_avg_prime_pow7 = _172;
    _174 = pow(25, 7);
    goto bb49;
bb49:
    _175 = (c_avg_prime_pow7 + _174);
    _176 = (c_avg_prime_pow7 / _175);
    _177 = sqrt(_176);
    goto bb50;
bb50:
    _178 = (2 * _177);
    rc = _178;
    _180 = (h_avg_prime - 275);
    _181 = (_180 / 25);
    _182 = pow(_181, 2);
    goto bb51;
bb51:
    _183 = (-_182);
    _184 = exp(_183);
    goto bb52;
bb52:
    _185 = (30 * _184);
    delta_theta = _185;
    _187 = (2 * delta_theta);
    _188 = (_187 * pi);
    _189 = (_188 / 180);
    _190 = sin(_189);
    goto bb53;
bb53:
    _191 = (rc * _190);
    _192 = (0 - _191);
    rt = _192;
    _194 = (kl * sl);
    _195 = (dl_prime / _194);
    term_l = _195;
    _197 = (kc * sc);
    _198 = (dc_prime / _197);
    term_c = _198;
    _200 = (kh * sh);
    _201 = (dh_prime_capital / _200);
    term_h = _201;
    _203 = (term_l * term_l);
    _204 = (term_c * term_c);
    _205 = (_203 + _204);
    _206 = (term_h * term_h);
    _207 = (_205 + _206);
    _208 = (rt * term_c);
    _209 = (_208 * term_h);
    _210 = (_207 + _209);
    _211 = sqrt(_210);
    goto bb54;
bb54:
    fflush(stdout);
    return _211;
}

static RGB tonemap_reinhard(RGB rgb) {
    RGB _ret;
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    RGB _14;

    _2 = rgb.r;
    _3 = rgb.r;
    _4 = (1 + _3);
    _5 = (_2 / _4);
    _6 = rgb.g;
    _7 = rgb.g;
    _8 = (1 + _7);
    _9 = (_6 / _8);
    _10 = rgb.b;
    _11 = rgb.b;
    _12 = (1 + _11);
    _13 = (_10 / _12);
    _14 = RGB_new(_5, _9, _13);
    goto bb1;
bb1:
    fflush(stdout);
    return _14;
}

static RGB tonemap_reinhard_extended(RGB rgb, double white) {
    RGB _ret;
    double _3;
    double w2;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    double _14;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    double _20;
    double _21;
    double _22;
    double _23;
    double _24;
    double _25;
    double _26;
    double _27;
    double _28;
    RGB _29;

    _3 = (white * white);
    w2 = _3;
    _5 = rgb.r;
    _6 = rgb.r;
    _7 = (_6 / w2);
    _8 = (1 + _7);
    _9 = (_5 * _8);
    _10 = rgb.r;
    _11 = (1 + _10);
    _12 = (_9 / _11);
    _13 = rgb.g;
    _14 = rgb.g;
    _15 = (_14 / w2);
    _16 = (1 + _15);
    _17 = (_13 * _16);
    _18 = rgb.g;
    _19 = (1 + _18);
    _20 = (_17 / _19);
    _21 = rgb.b;
    _22 = rgb.b;
    _23 = (_22 / w2);
    _24 = (1 + _23);
    _25 = (_21 * _24);
    _26 = rgb.b;
    _27 = (1 + _26);
    _28 = (_25 / _27);
    _29 = RGB_new(_12, _20, _28);
    goto bb1;
bb1:
    fflush(stdout);
    return _29;
}

static RGB tonemap_apply_with_exposure(RGB rgb, double exposure) {
    RGB _ret;
    double _3;
    double scale;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    RGB _11;
    RGB exposed;
    int32_t _13;

    _3 = pow(2, exposure);
    goto bb1;
bb1:
    scale = _3;
    _5 = rgb.r;
    _6 = (_5 * scale);
    _7 = rgb.g;
    _8 = (_7 * scale);
    _9 = rgb.b;
    _10 = (_9 * scale);
    _11 = RGB_new(_6, _8, _10);
    goto bb2;
bb2:
    exposed = _11;
    _13 = reinhard(exposed);
    goto bb3;
bb3:
    fflush(stdout);
    return _13;
}

int32_t main(void) {
    __quanta_init_io();
    int32_t _ret;
    Vec3 _1;
    Vec3 v1;
    Vec3 _3;
    Vec3 v2;
    Vec3* _5;
    Vec3* _6;
    double _7;
    double dot;
    Vec3* _9;
    double _10;
    double len;
    int8_t* _12;
    int8_t* _13;
    int8_t* _14;
    int8_t* _15;
    int8_t* _16;
    int8_t* _17;
    int8_t* _18;
    Mat3 _19;
    Mat3 identity;
    Vec3 _21;
    Vec3 v;
    Mat3* _23;
    Vec3* _24;
    Vec3 _25;
    Vec3 result;
    double _27;
    double _28;
    double _29;
    int8_t* _30;
    int8_t* _31;
    int8_t* _32;
    RGB _33;
    RGB srgb;
    RGB _35;
    RGB linear;
    double _37;
    double _38;
    double _39;
    int8_t* _40;
    XYZ _41;
    XYZ xyz;
    double _43;
    double _44;
    double _45;
    int8_t* _46;
    int8_t* _47;
    int8_t* _48;
    Lab _49;
    Lab lab;
    double _51;
    double _52;
    double _53;
    int8_t* _54;
    Lab* _55;
    double _56;
    int8_t* _57;
    int8_t* _58;
    int8_t* _59;
    RGB _60;
    Lab _61;
    Lab lab_direct;
    double _63;
    double _64;
    double _65;
    int8_t* _66;
    int8_t* _67;
    int8_t* _68;
    RGB _69;
    Lab _70;
    Lab lab_red;
    RGB _72;
    Lab _73;
    Lab lab_green;
    RGB _75;
    Lab _76;
    Lab lab_blue;
    double _78;
    double de_rg;
    double _80;
    double de_rb;
    double _82;
    double de_self;
    int8_t* _84;
    int8_t* _85;
    int8_t* _86;
    double _87;
    double de76;
    int8_t* _89;
    int8_t* _90;
    int8_t* _91;
    RGB _92;
    RGB hdr_color;
    RGB _94;
    RGB tonemapped;
    double _96;
    double _97;
    double _98;
    int8_t* _99;
    RGB _100;
    RGB _101;
    RGB exposed;
    double _103;
    double _104;
    double _105;
    int8_t* _106;
    RGB _107;
    RGB ext;
    double _109;
    double _110;
    double _111;
    int8_t* _112;
    int8_t* _113;
    int8_t* _114;
    RGB _115;
    RGB col;
    RGB* _117;
    double _118;
    int8_t* _119;
    double _120;
    RGB _121;
    RGB over;
    RGB* _123;
    RGB _124;
    RGB clamped;
    double _126;
    double _127;
    double _128;
    int8_t* _129;
    int8_t* _130;
    int8_t* _131;
    Mat3 m;
    Mat3* _133;
    Mat3 _134;
    Mat3* _135;
    Mat3 _136;
    Mat3 m2;
    double _138[3][3];
    double _139[3];
    double _140;
    int8_t* _141;
    double _142[3][3];
    double _143[3];
    double _144;
    int8_t* _145;
    int8_t* _146;
    int8_t* _147;
    RGB _148;
    RGB original;
    RGB _150;
    RGB lin;
    RGB _152;
    RGB back;
    int8_t* _154;
    double _155;
    double _156;
    double _157;
    int8_t* _158;
    int8_t* _159;
    int8_t* _160;

    _1 = Vec3_new(1, 0, 0);
    goto bb1;
bb1:
    v1 = _1;
    _3 = Vec3_new(0, 1, 0);
    goto bb2;
bb2:
    v2 = _3;
    _5 = &v1;
    _6 = &v2;
    _7 = Vec3_dot(_5, _6);
    goto bb3;
bb3:
    dot = _7;
    _9 = &v1;
    _10 = Vec3_length(_9);
    goto bb4;
bb4:
    len = _10;
    _12 = __str0;
    printf(_12);
    goto bb5;
bb5:
    _13 = __str1;
    printf(_13);
    goto bb6;
bb6:
    _14 = __str2;
    printf(_14);
    goto bb7;
bb7:
    _15 = __str3;
    printf(_15, dot);
    goto bb8;
bb8:
    _16 = __str4;
    printf(_16, len);
    goto bb9;
bb9:
    _17 = __str1;
    printf(_17);
    goto bb10;
bb10:
    _18 = __str5;
    printf(_18);
    goto bb11;
bb11:
    _19 = Mat3_identity();
    goto bb12;
bb12:
    identity = _19;
    _21 = Vec3_new(0.5, 0.3, 0.2);
    goto bb13;
bb13:
    v = _21;
    _23 = &identity;
    _24 = &v;
    _25 = Mat3_mul_vec3(_23, _24);
    goto bb14;
bb14:
    result = _25;
    _27 = result.x;
    _28 = result.y;
    _29 = result.z;
    _30 = __str6;
    printf(_30, _27, _28, _29);
    goto bb15;
bb15:
    _31 = __str1;
    printf(_31);
    goto bb16;
bb16:
    _32 = __str7;
    printf(_32);
    goto bb17;
bb17:
    _33 = RGB_new(0.5, 0.3, 0.2);
    goto bb18;
bb18:
    srgb = _33;
    _35 = convert_srgb_to_linear(srgb);
    goto bb19;
bb19:
    linear = _35;
    _37 = linear.r;
    _38 = linear.g;
    _39 = linear.b;
    _40 = __str8;
    printf(_40, _37, _38, _39);
    goto bb20;
bb20:
    _41 = convert_srgb_to_xyz(linear);
    goto bb21;
bb21:
    xyz = _41;
    _43 = xyz.x;
    _44 = xyz.y;
    _45 = xyz.z;
    _46 = __str9;
    printf(_46, _43, _44, _45);
    goto bb22;
bb22:
    _47 = __str1;
    printf(_47);
    goto bb23;
bb23:
    _48 = __str10;
    printf(_48);
    goto bb24;
bb24:
    _49 = convert_xyz_to_lab(xyz);
    goto bb25;
bb25:
    lab = _49;
    _51 = lab.l;
    _52 = lab.a;
    _53 = lab.b;
    _54 = __str11;
    printf(_54, _51, _52, _53);
    goto bb26;
bb26:
    _55 = &lab;
    _56 = Lab_chroma(_55);
    goto bb27;
bb27:
    _57 = __str12;
    printf(_57, _56);
    goto bb28;
bb28:
    _58 = __str1;
    printf(_58);
    goto bb29;
bb29:
    _59 = __str13;
    printf(_59);
    goto bb30;
bb30:
    _60 = RGB_new(0.5, 0.3, 0.2);
    goto bb31;
bb31:
    _61 = convert_srgb_to_lab(_60);
    goto bb32;
bb32:
    lab_direct = _61;
    _63 = lab_direct.l;
    _64 = lab_direct.a;
    _65 = lab_direct.b;
    _66 = __str14;
    printf(_66, _63, _64, _65);
    goto bb33;
bb33:
    _67 = __str1;
    printf(_67);
    goto bb34;
bb34:
    _68 = __str15;
    printf(_68);
    goto bb35;
bb35:
    _69 = RGB_new(1, 0, 0);
    goto bb36;
bb36:
    _70 = convert_srgb_to_lab(_69);
    goto bb37;
bb37:
    lab_red = _70;
    _72 = RGB_new(0, 1, 0);
    goto bb38;
bb38:
    _73 = convert_srgb_to_lab(_72);
    goto bb39;
bb39:
    lab_green = _73;
    _75 = RGB_new(0, 0, 1);
    goto bb40;
bb40:
    _76 = convert_srgb_to_lab(_75);
    goto bb41;
bb41:
    lab_blue = _76;
    _78 = color_difference_delta_e_2000(lab_red, lab_green, 1, 1, 1);
    goto bb42;
bb42:
    de_rg = _78;
    _80 = color_difference_delta_e_2000(lab_red, lab_blue, 1, 1, 1);
    goto bb43;
bb43:
    de_rb = _80;
    _82 = color_difference_delta_e_2000(lab_red, lab_red, 1, 1, 1);
    goto bb44;
bb44:
    de_self = _82;
    _84 = __str16;
    printf(_84, de_rg);
    goto bb45;
bb45:
    _85 = __str17;
    printf(_85, de_rb);
    goto bb46;
bb46:
    _86 = __str18;
    printf(_86, de_self);
    goto bb47;
bb47:
    _87 = color_difference_delta_e_76(lab_red, lab_green);
    goto bb48;
bb48:
    de76 = _87;
    _89 = __str19;
    printf(_89, de76);
    goto bb49;
bb49:
    _90 = __str1;
    printf(_90);
    goto bb50;
bb50:
    _91 = __str20;
    printf(_91);
    goto bb51;
bb51:
    _92 = RGB_new(4, 2, 1);
    goto bb52;
bb52:
    hdr_color = _92;
    _94 = tonemap_reinhard(hdr_color);
    goto bb53;
bb53:
    tonemapped = _94;
    _96 = tonemapped.r;
    _97 = tonemapped.g;
    _98 = tonemapped.b;
    _99 = __str21;
    printf(_99, _96, _97, _98);
    goto bb54;
bb54:
    _100 = RGB_new(0.5, 0.3, 0.2);
    goto bb55;
bb55:
    _101 = tonemap_apply_with_exposure(_100, 2);
    goto bb56;
bb56:
    exposed = _101;
    _103 = exposed.r;
    _104 = exposed.g;
    _105 = exposed.b;
    _106 = __str22;
    printf(_106, _103, _104, _105);
    goto bb57;
bb57:
    _107 = tonemap_reinhard_extended(hdr_color, 6);
    goto bb58;
bb58:
    ext = _107;
    _109 = ext.r;
    _110 = ext.g;
    _111 = ext.b;
    _112 = __str23;
    printf(_112, _109, _110, _111);
    goto bb59;
bb59:
    _113 = __str1;
    printf(_113);
    goto bb60;
bb60:
    _114 = __str24;
    printf(_114);
    goto bb61;
bb61:
    _115 = RGB_new(0.8, 0.4, 0.2);
    goto bb62;
bb62:
    col = _115;
    _117 = &col;
    _118 = RGB_luminance(_117);
    goto bb63;
bb63:
    _119 = __str25;
    printf(_119, _118);
    goto bb64;
bb64:
    _120 = (-0.3);
    _121 = RGB_new(1.5, _120, 0.7);
    goto bb65;
bb65:
    over = _121;
    _123 = &over;
    _124 = RGB_saturate(_123);
    goto bb66;
bb66:
    clamped = _124;
    _126 = clamped.r;
    _127 = clamped.g;
    _128 = clamped.b;
    _129 = __str26;
    printf(_129, _126, _127, _128);
    goto bb67;
bb67:
    _130 = __str1;
    printf(_130);
    goto bb68;
bb68:
    _131 = __str27;
    printf(_131);
    goto bb69;
bb69:
    m = matrices_SRGB_TO_XYZ;
    _133 = &m;
    _134 = Mat3_identity();
    goto bb70;
bb70:
    _135 = &_134;
    _136 = Mat3_mul_mat3(_133, _135);
    goto bb71;
bb71:
    m2 = _136;
    memcpy(_138, &(m2.m), sizeof(_138));
    memcpy(_139, &(_138[0]), sizeof(_139));
    _140 = _139[0];
    _141 = __str28;
    printf(_141, _140);
    goto bb72;
bb72:
    memcpy(_142, &(m2.m), sizeof(_142));
    memcpy(_143, &(_142[1]), sizeof(_143));
    _144 = _143[1];
    _145 = __str29;
    printf(_145, _144);
    goto bb73;
bb73:
    _146 = __str1;
    printf(_146);
    goto bb74;
bb74:
    _147 = __str30;
    printf(_147);
    goto bb75;
bb75:
    _148 = RGB_new(0.5, 0.3, 0.2);
    goto bb76;
bb76:
    original = _148;
    _150 = convert_srgb_to_linear(original);
    goto bb77;
bb77:
    lin = _150;
    _152 = convert_linear_to_srgb(lin);
    goto bb78;
bb78:
    back = _152;
    _154 = __str31;
    printf(_154);
    goto bb79;
bb79:
    _155 = back.r;
    _156 = back.g;
    _157 = back.b;
    _158 = __str32;
    printf(_158, _155, _156, _157);
    goto bb80;
bb80:
    _159 = __str1;
    printf(_159);
    goto bb81;
bb81:
    _160 = __str33;
    printf(_160);
    goto bb82;
bb82:
    fflush(stdout);
    return 0;
}

